### ISSUE TITLE
The StorageClass configuration does not used

### ISSUE THREAD

**Issue by whg517** [zncdatadev/spark-k8s-operator#56]
During component configuration, you can specify storageclass for PVC through resource, but the default storageclass is used instead of taking effect during actual running.

```yaml
        config:
          resources:
            storage:
              data:
                storageClass: foo
```
